name: gnr_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.4.0+cu126 --extra-index-url https://download.pytorch.org/whl/cu126
    - torchvision --extra-index-url https://download.pytorch.org/whl/cu126
    - git+https://github.com/huggingface/transformers
    - accelerate>=0.34.0
    - qwen-vl-utils
    - Pillow
    - pandas
    - huggingface_hub
    - sentencepiece
    - tiktoken
    - einops
    - flash-attn