name: gnr_project_env1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - git+https://github.com/huggingface/transformers
    - accelerate>=0.34.0
    - qwen-vl-utils
    - Pillow
    - pandas
    - huggingface_hub
    - sentencepiece
    - tiktoken
    - einops
